# **UNIDAD TEMÁTICA II: Manejo y análisis de datos**

*   Arreglos unidimensionales y multidimensionales.   Operaciones entre arreglos. Redimensionamiento. Conversiones de tipos. Concatenación. Generación de arreglos aleatorios y de secuencias de datos. Comparación de arreglos. 
*   <font color='blue'>Numpy</font>

## **<center>Arrays / Arreglos</center>**

Python está organizado en ***módulos***, que son archivos con extensión **.py** que contienen funciones, variables y otros objetos... y **paquetes, que son conjuntos de módulos**.

Cuando queremos utilizar objetos que están definidos en un módulo tenemos que importarlo, y una vez que lo hemos hecho podemos usar el operador **.** para ir descendiendo en la jerarquía de paquetes y acceder al objeto que necesitamos. Por ejemplo, de esta manera importamos <font color='blue'>NumPy:</font>

In [ ]:
import numpy as np

In [ ]:
np.all

<function numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)>

**Qué es NumPy?**

Hasta ahora habran visto los tipos de datos más básicos que nos ofrece Python: str, integer, boolean, list, tuple... Pero ¿que hay de los vectores, matrices...?

El paquete numpy es usado en casi todos los cálculos numéricos usando Python. Es un paquete que provee a Python de estructuras de datos vectoriales, matriciales y de rango mayor (de alto rendimiento). Proporciona un objeto tipo **array** para almacenar datos de forma eficiente y una serie de funciones para operar y manipular esos datos

¿Qué solemos guardar en arrays?

*   Vectores y matrices
*   Datos de experimentos: En distintos instantes discretos. En distintos puntos del espacio
*   Discretizaciones para usar algoritmos de: integración, derivación, interpolación...

**Array de una dimensión**

Un array de NumPy es una colección de N elementos, igual que una secuencia de Python (por ejemplo, una lista). Tiene las mismas propiedades que una secuencia y algunas más:

Los arreglos nos permiten realizar operaciones sobre todos los elementos a la vez en una misma operación; con las listas debemos realizar las operaciones sobre cada elemento individualmente.

Nuestro primer array: Los arrays de una dimensión se crean pasándole una lista como argumento a la función **np.array**

In [ ]:
mi_primer_array = np.array([1, 2, 3, 4]) 
mi_primer_array

array([1, 2, 3, 4])

In [ ]:
# Podemos usar print
print(mi_primer_array)

[1 2 3 4]


In [ ]:
# Comprobar el tipo de mi_primer_array
type(mi_primer_array)

numpy.ndarray

Los arrays de NumPy son homogéneos, es decir, todos sus elementos son del mismo tipo. Si le pasamos a np.array una secuencia con objetos de tipos diferentes, promocionará todos al tipo con más información. Para acceder al tipo del array, podemos usar el atributo **dtype**


In [ ]:
# Comprobar el tipo de datos que contiene
mi_primer_array.dtype

dtype('int64')

In [ ]:
# EJEMPLO VISTO EN LA CLASE: 
# Vemos que si ponemos un numero decimal en un arreglo de enteros, numpy elige el tipo "float" para el array (aunque el resto 
# sean todos enteros).
mi_primer_array = np.array([1, 2, 3.0, 4])
print(mi_primer_array.dtype)

float64


**Array multidimensional**

Para crear un array de dos dimensiones le pasaremos una lista de listas:

In [ ]:
# Array de dos dimensiones
mi_segundo_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
print(mi_segundo_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Esto sería una buena manera de definirlo, de acuerdo con el PEP 8 (indentation)

Nota: Guia de estilo de Python
https://peps.python.org/pep-0008/

In [ ]:
mi_segundo_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]) 

**Funciones y constantes de NumPy**

Hemos dicho que NumPy también incorporá funciones. Un ejemplo sencillo:

In [ ]:
print(mi_primer_array)

[1 2 3 4]


In [ ]:
# Suma
np.sum(mi_primer_array)

10.0

In [ ]:
# Máximo / minimo
print(np.min(mi_primer_array))
print(np.max(mi_primer_array))

1
4


In [ ]:
print(mi_segundo_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Seno
np.sin(mi_segundo_array)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

**Nota**: Si NumPy no entiende el tipo de datos o construimos un array con argumentos incorrectos devolverá un array con dtype `object`. Estos arrays rara vez son útiles y su aparición suele ser signo de que algo falla en nuestro programa.

NumPy intentará automáticamente construir un array con el tipo adecuado teniendo en cuenta los datos de entrada, aunque nosotros podemos forzarlo.



In [ ]:
# Ejemplo forzando el tipo de dato. A pesar que todos los numeros son enteros (y por defecto construiria un arreglo de "int"),
# podemos forzar a que el tipo de dato del arreglo sea "float".
a = np.array([1, 2, 3], dtype=float)
print(a.dtype)
print(a)

float64
[1. 2. 3.]


In [ ]:
# Otro ejemplo forzando tipo de dato.
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

Además de arrays, NumPy contiene también constantes y funciones matemáticas de uso cotidiano

In [ ]:
np.e

2.718281828459045

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.log(2)

0.6931471805599453

**Funciones para crear arrays**

In [ ]:
# En una dimensión 
# Crea un arreglo con tantos ceros como se indique.
a = np.zeros(25)
print(a.shape)
print(a)

(25,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [ ]:
# En dos (o más) dimensiones
# Crea una matriz de las dimensiones indicadas con ceros.
a = np.zeros([10,10])
print(a.shape)
print(a.dtype)
print(a)

(10, 10)
int8
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a = np.identity(4)
print(a.shape)
print(a)

(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Ejercicio:**

*   Crear un array z1 3x4 lleno de ceros de tipo entero.
*   Crear un array z2 3x4 lleno de ceros salvo la primera fila que serán todo unos. (resuelto mas abajo)
*   Crear un array z3 3x4 lleno de ceros salvo la última fila que será el rango entre 5 y 8. (resuelto mas abajo)

In [ ]:
# Crear un array z1 3x4 lleno de ceros de tipo entero.
z1=np.zeros([3,4], dtype=int)
print(z1)
print(z1.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


**Rangos:**

NumPy, dame un array que vaya de 0 a 5:

In [ ]:
#desde el numero que inicia el arreglo hasta el SIGUIENTE del ultimo numero, puedo aclarar el paso que da con el parametro step
# np.arange(start, stop, step)
a = np.arange(0, 5)   
a

array([0, 1, 2, 3, 4])

Mira con atención el resultado anterior, ¿hay algo que deberías grabar en tu cabeza para simpre? El último elemento no es 5 sino 4 y el primer elemento va a ser 0.

**Ejercicio:**
NumPy, dame un array que vaya de 0 a 10, de 3 en 3:



In [ ]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

**Indexación de arrays:**

Una de las herramientas más importantes a la hora de trabajar con arrays es el indexado. Consiste en seleccionar elementos aislados o secciones de un array. Nosotros vamos a ver la indexación básica, pero existen técnicas de indexación avanzada que convierten los arrays en herramientas potentísimas.

In [ ]:
a = np.arange(2,15) #creo el arreglo ejemplo
print(a)            #muestro el arreglo entero
print(' ')          #pongo esto nada mas para que aparezcan separados los mensajes por un renglon
print(a[8])         #muestro el indice 8 (lugar 9) del arreglo (indice = lugar -1)

a[8]=125            #modifico el elemento en la posicion 8 del arreglo
print(' ')
print(a)            #muestro el arreglo modificado

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
10
[  2   3   4   5   6   7   8   9 125  11  12  13  14]


Los índices se indican entre corchetes justo después del array. Recuerda que en Python **la indexación empieza en 0**. Si recuperamos el primer elemento de un array de dos dimensiones, obtenemos la primera fila.

In [ ]:
# Recupero la fila 0.
a[0]

array([1, 2, 3, 4, 5, 6])

Para recuperar el primer elemento de la primera fila, podemos abreviar aún más la sintaxis:



In [ ]:
# Recupero el elemento en la fila 1, columna 5.
a[1, 5]

12

In [ ]:
#En este bloque MODIFICO el elemento de la fila 1, columna 5 y muestro el arreglo antes y despues.
print(a)
a[1,5]=0    #aca modifico el elemento
print(' ')  #esto para que haya un espacio en el medio cuando muestro el arreglo antes y despues
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  0]]


No solo podemos recuperar un elemento aislado, sino también porciones del array, utilizando la sintaxis **[inicio : final : salto]**

Veamos algunos ejemplos continuando con el ejemplo anterior: El inicio se incluye pero el fin se excluye



In [ ]:
arr = np.array([12, 23, 34, 45, 56, 67, 78, 89, 91])

In [ ]:
arr[3:9]   #NO TOMA el ultimo valor, es hasta el anterior (si quiero hasta el indice 8, pongo segundo numero 9)

array([45, 56, 67, 78, 89, 91])

In [ ]:
arr[2:5]

array([34, 45, 56])

In [ ]:
arr[0:7:2]   #inicio, final, step

array([12, 34, 56, 78])

Si omitimos *inicio* o *fin* significa desde el inicio o hasta el final respectivamente (todos):

In [ ]:
arr[2:]

array([34, 45, 56, 67, 78, 89, 91])

In [ ]:
arr[:3]

array([12, 23, 34])

**Insertando, modificando y eliminando elementos**

Los arreglos de NumPy son de tamaño fijo así que para insertar o eliminar elementos se debe crear un nuevo a arreglo.
Para insertar elementos al final del arreglo utilizamos el método **append**:

In [ ]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
# agregar un elemento
np.append(arr, 4)

array([1, 2, 3, 4])

In [ ]:
# agregar una lista
np.append(arr, [4, 5, 6])

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

Recuerda que arr no se modifica cuando utilizamos append, debemos asignar el resultado a una nueva variable o reasignar la variable inicial:

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
nuevo_arr = np.append(arr, [4, 5, 6])
print(nuevo_arr)

[1 2 3 4 5 6 4 5 6]


Para insertar elementos en otras posiciones del arreglo podemos utilizar el método **insert**. 

Por ejemplo, para insertar el número 5 en la posición 1 haríamos lo siguiente:


In [ ]:
arr = np.array([1, 2, 3])
np.insert(arr, 1, 5)

array([1, 5, 2, 3])

Podemos modificar los elementos de un arreglo igual que lo haríamos con una lista:

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[2] = 100
print(arr)

[  1   2 100   4]


Para eliminar elementos de un arreglo podemos utilizar el método **delete**:

In [ ]:
arr = np.array([1, 2, 3, 4])
np.delete(arr, 0)

array([2, 3, 4])

In [ ]:
# podemos utilizar un rango
np.delete(arr, slice(1, 3))

array([1, 4])

In [ ]:
# podemos utilizar una lista de índices
np.delete(arr, [0, 2])

array([2, 4])

#Los ejercicios que dejamos antes colgados

*   Crear un array z2 3x4 lleno de ceros salvo la primera fila que serán todo unos. 
*   Crear un array z3 3x4 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [ ]:
#Crear un array z2 3x4 lleno de ceros salvo la primera fila que serán todo unos. 

z2 = np.zeros([3,4])
print(z2)
print(' ')

z2[0, : ] = 1  #modifico los elementos de la fila 0, en TODAS las columnas (pues hay un ":" sin inicio ni final)
print(z2)

In [ ]:
#Crear un array z3 3x4 lleno de ceros salvo la última fila que será el rango entre 5 y 8.
z3=np.zeros([3,4])
print(z3)
print(' ')

z3[2, : ] = [5, 6, 7, 8]   # otra forma de hacer esto es poner      z3[2, : ] =  np.arange(5,9)
print(z3)

In [ ]:
# Ejemplo para reemplazar determinadas filas y columnas
a=np.zeros([3,4])
print(a)
print(' ')

a[1:3, 1:3 ] = [[5, 6],     
                [4, 3]]   
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[0. 0. 0. 0.]
 [0. 5. 6. 0.]
 [0. 4. 3. 0.]]


#Seguimos 

**Operaciones matemáticas**

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
# sumar
arr + 3

array([4, 5, 6])

In [ ]:
# multiplicar
arr * 2 

array([2, 4, 6])

Las operaciones también pueden ser con otros arreglos de NumPy. Por ejemplo:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

c = a + b
print(c)

[ 7  9 11 13 15]


Cuando realizas operaciones matemáticas entre arreglos, los dos arreglos deben tener la misma longitud. De lo contrario se genera un error. Por ejemplo:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8])

a + b

ValueError: ignored

Cuando aplicamos operaciones lógicas sobre los arreglos, cada elemento es evaluado y se genera un nuevo arreglo de booleanos:

In [ ]:
arr = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
arr > 5

array([ True, False, False, False, False, False,  True,  True,  True,
        True])

**Otras operaciones comunes**

In [ ]:
arr = np.array([1, 2, 3, 4])

# Dividir en partes iguales
np.split(arr, 2)

[array([1, 2]), array([3, 4])]

In [ ]:
arr = np.array([5, 2, 8, 7])

# Ordenar (retorna un nuevo arreglo)
ordenado = np.sort(arr)

print(arr)          #no se modifica el arreglo original!!!
print(ordenado)

[5 2 8 7]
[2 5 7 8]


In [ ]:
arr = [1, 1, 2, 2, 3, 3]

# Obtener los elementos únicos
np.unique(arr)

array([1, 2, 3])

In [ ]:
arr = np.array([1, 2, 3, 4])

# Obtener el promedio
np.mean(arr)

2.5

**Tamaños del arreglo:**

Para conocer el número de elementos de un arreglo usamos el atributo **size**

In [ ]:
arr = np.array([
  [1, 2],
  [3, 4]
])

In [ ]:
print(arr.size)         #cantidad de elementos
print(arr.shape)        #forma del arreglo

4
(4,)


Sin embargo, a veces es útil también saber la forma de un arreglo, es decir, la longitud de cada una de las dimensiones. Para esto podemos utilizar el atributo **shape**:

In [ ]:
arr.shape

(2, 2)

![matriz](https://raw.githubusercontent.com/gersongams/CursoPython/3d060c0cb9fea55e2fd2318563124d5698d88e30/images/matrizslice.png)

**Cambiando la forma de un arreglo**

Para cambiar la forma de un arreglo utilizamos el método reshape. Por ejemplo, aunque el método arange no permite especificar la forma, podemos cambiar la forma con **reshape**:

In [ ]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [ ]:
print(arr)
print(' ')
a = arr.reshape((2, 3)) #cambio las dimensiones del arreglo de 6x1 a 3x2
print(a)
print(' ')
b = a.reshape(6)
print(b)

In [ ]:
# o en una sola línea
np.arange(6).reshape((3, 2))

Obteniendo valores de un arreglo multidimensional
Para obtener los valores de un arreglo multidimensional debemos especificar los índices en cada dimensión. Por ejemplo, para obtener un valor en un arreglo de dos dimensiones debemos pasar dos índices:

In [ ]:
arr = np.array([
  [1, 2],
  [3, 4]
])

In [ ]:
arr[0, 0]

1

In [ ]:
arr[1, 0]

3

Si queremos seleccionar la columna entera pasamos dos puntos (:) como primer índice:

In [ ]:
arr[:,0]

array([1, 3])

Si queremos seleccionar la fila entera pasamos dos puntos (:) como segundo índice:

In [ ]:
arr[1,:]

array([3, 4])

In [ ]:
arr = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

arr[1:, :2]

array([[4, 5],
       [7, 8]])

**Ejercicio:**

*   Crea un vector de 10 elementos, siendo los impares unos y los pares doses.
*   Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas.



In [ ]:
# Crea un vector de 10 elementos, siendo los impares unos y los pares doses.
vector = np.ones(10)    # Creo un vector de "1", pues es uno de los valores que necesito.
print(vector)           # Muestro el vector.
vector[0:11:2] = 2      # Voy reemplazando desde el elemento cero hasta el 10 (recordar que se pone uno mas como final, por eso el 11).
                        # Elegimos un paso de 2 pues queremos que reemplace un elemento si, un elemento no.
                        # Recordar siempre (start:stop:step)
print(' ')
print(vector)           #Muestro el vector modificado.

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 
[2. 1. 2. 1. 2. 1. 2. 1. 2. 1.]


In [ ]:
# Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas.

#La idea es primero crear el tablero, luego generar un vector para fila par y otro para fila impar.
#Luego se reemplaza en el tablero fila par y fila impar intercaladas.

ajedrez = np.ones([8,8])    # Genero el tablero. 
print(ajedrez)              # Muestro el tablero.

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
fila_par = np.zeros(8)  # Creo un vector que sera la fila par con base de "0".
fila_par[1:9:2] = 1     # Reemplazo elementos intercalados con "1". El primer elemento lo dejo como cero (comienzo de la posicion 1).
print(fila_par)         # Muestro la fila par.

[0. 1. 0. 1. 0. 1. 0. 1.]


In [ ]:
fila_impar = np.zeros(8) # Creo un vector que sera la fila par con base de "0".
fila_impar[0:9:2] = 1    # Reemplazo elementos intercalados con "1". 
print(fila_impar)        # Muestro la fila impar.

[1. 0. 1. 0. 1. 0. 1. 0.]


In [ ]:
for index in range(0,8):            # Recorro todas las columnas del ajedrez. 
    if ((index % 2) == 0 ):         # Si el indice es par...
        ajedrez[index]=fila_par     # ...reemplazo la fila par.
    else:                           # Si el indice es impar....
        ajedrez[index]=fila_impar   # ...reemplazo la fila impar.

print(ajedrez)                      # Muestro el ajedrez final.

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Funciones estadísticas:**

**Media o promedio**

El primer concepto estadístico que exploramos será la media (mean), comúnmente conocida como el promedio. Es útil para obtener el centro de un dataset. NumPy incluye una función para calcular la media de los arreglos: np.mean.

In [ ]:
arr = np.array([5, 10.4, 4, 3, 6.6])
np.mean(arr)

5.8

**Redondeando**

Podemos redondear la media a un número específico de puntos decimales? Sí, podemos usar la función de Python round() el cual recibe dos parámetros: número a redondear y número de decimales. NumPy nos provee también una forma de redondear cada valor en un array a través de la función np.round(). Funciona similar al round de python porque recibe ambos parámetros.

In [ ]:
# redondeando un número con Python
numero = 1.234
print(round(numero, 2))
print(round(numero))

1.23
1


In [ ]:
# redondeando un array con NumPy
array = np.array([1.11, 2.22, 3.33, 4.44])
print(np.round(array, 1))

[1.1 2.2 3.3 4.4]


**Media de los valores**

Que pasa si queremos obtener la media de los valores en vez del porcentaje de valores, que satisfacen una condición? por demos hacerlo así:
Digamos que tenemos un array de temperaturas desde -20 hasta 50 y queremos obtener el promedio de temperaturas mayores a 10.

In [ ]:
temperaturas = np.array(list(range(-20, 55, 5)))
temperaturas

array([-20, -15, -10,  -5,   0,   5,  10,  15,  20,  25,  30,  35,  40,
        45,  50])

Primero seleccionamos los datos específicos basados en una condición, el cual creará un nuevo array para todas las temperaturas mayores a 10 temperaturas[temperaturas > 10]

Finalmente aplicamos la función np.mean() a estos datos, y nos dará la media de los valores que cumplen con ese condicional:

In [ ]:
temperaturas = np.array(list(range(-20, 55, 5)))
np.mean(temperaturas[temperaturas > 10])

32.5

In [ ]:
#desglose de la ultima linea del bloque anterior
print(temperaturas)
print(' ')
condicion = (temperaturas>10)
print(condicion)
print(' ')
temperaturas_mayor_a_10=temperaturas[condicion]
print(temperaturas_mayor_a_10)
print(' ')
print(np.mean(temperaturas_mayor_a_10))

[-20 -15 -10  -5   0   5  10  15  20  25  30  35  40  45  50]
 
[False False False False False False False  True  True  True  True  True
  True  True  True]
 
[15 20 25 30 35 40 45 50]
 
32.5


**Mediana**

Otra métrica importante que podemos usar para el análisis de datos es la mediana (median). La mediana es el valor del medio de un set de datos que ha sido ordenado en términos de magnitud (del más pequeño al más grande)
Si el largo del set de datos es un número impar, la mediana sería el valor central (recuerde que la lista debe estar primero ordenada de menor a mayor). Así que en el siguiente ejemplo, la mediana sería 3

In [ ]:
numeros = [1, 1, 2, 3, 4, 5, 5]
numeros = np.array(numeros)

np.median(numeros)

3.0

Si el largo del set de datos es un número par, la mediana sería el valor a medio camino entre los dos valores centrales. Así que en el siguiente ejemplo, la mediana sería 3.5

In [ ]:
numeros = [1, 1, 2, 3, 4, 5, 5, 6]
numeros = np.array(numeros)

np.median(numeros)

3.5

Diferencias entre la Media y la Mediana:

Algunas veces estos dos valores serán muy similares según el set de datos, pero son diferentes y representan conceptos diferentes. La mediana retorna el valor en una posición central de un dataset ordenado. Si el largo del dataset es par, será el promedio de los dos valores del medio. Es conocido también como el "50th percentile". La media es el promedio de todos los valores del set de datos.

In [ ]:
valores = [1, 1, 1, 2, 900]
valores = np.array(valores)

In [ ]:
np.mean(valores)

181.0

In [ ]:
np.median(valores)

1.0

**Broadcasting**

Broadcasting es un potente mecanismo que permite a numpy trabajar con matrices de diferentes formas al realizar operaciones aritméticas. Con frecuencia tenemos una matriz más pequeña y una matriz más grande, y queremos usar la matriz más pequeña varias veces para realizar alguna operación en la matriz más grande.

![Broadcasting](https://raw.githubusercontent.com/gersongams/CursoPython/3d060c0cb9fea55e2fd2318563124d5698d88e30/images/numpy_broadcasting.png)

Por ejemplo, supongamos que queremos añadir un vector constante a cada fila de una matriz. Podríamos hacerlo así:


In [ ]:
# Vamos a añadir el vector V a cada fila de la matriz x
# guardando el resultado en la matriz y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = np.empty_like(x)   # Creamos una matriz vacia de la misma forma de X

# Añadimos el vector v a cada fila de la matriz X con un loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Esto funcionas, sin embargo, Numpy Broadcasting nos permite realizar este cálculo sin realmente crear múltiples copias de v. Considere esta versión, utilizando la Broadcasting:

In [ ]:
# Vamos a añadir el vector V a cada fila de la matriz x
# guardando el resultado en la matriz y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Añada v a cada fila de x mediante broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**Cargando y guardando arreglos en archivos CSV**

Para cargar y guardar arreglos en CSV (archivos separados por coma) utiliza los métodos loadtxt y savetxt

In [ ]:
arr = np.array([34,9,12,11,7])

# Guardar a un archivo CSV
np.savetxt('arreglo.csv', arr)

In [ ]:
# Cargar de un archivo CSV
nuevo_arr = np.loadtxt('arreglo.csv')

In [ ]:
print(nuevo_arr)

Para estudiar Numpy en casa: https://www.w3schools.com/python/numpy/default.asp